spring:
  cloud:
    azure:
      active-directory:
        b2c:
          enabled: true
          base-uri: https://ab2cpruebaintempo.b2clogin.com/ab2cpruebaintempo.onmicrosoft.com/
          credential:
            client-id: 8a207a32-b92e-4192-b80d-2b867ae4255c
            client-secret: O5A8Q~YVuPqDCPl6-H2FVOJ5LU~5wdLUzgreQa5Q
          login-flow: sign-up-or-sign-in
          logout-success-url: http://localhost:8080/logout
          user-flows:
            profile-edit: B2C_1_profileediting1
            sign-up-or-sign-in: B2C_1_signupsingin1